### ISSUE TITLE
Refactor Entire Hydra setup 

### ISSUE THREAD

**Issue by vsedov** [vsedov/nvim#48]
There is allot of repeating code that can be converted into a module , I will work on this in December hopefully. 

Sorry for the crap code >.<

**Comment by luxus** [comment]
looking forward to see the rewrite, i guess that is the biggest hydra setup on github

**Comment by vsedov** [comment]
Ah really wasnt expecting people to be looking forward to this, il try working on it this week then . Cheers.

**Comment by luxus** [comment]
no pressure, i searched for hydra setups and found yours,
if you are busy, I can live without it :D

**Comment by vsedov** [comment]
Yeah no worries mate, im finishing off some stuff, Im not really sure how to refactor it, cause there are the api modules, and there are the normal ones. with custom hints compared to the auto-generated ones.  

Im in the process of cleaning it up though. 


Most likely wil be done by the end of this week.

**Comment by luxus** [comment]
it will be hard to come up with all the mappings for your heads :D

**Comment by vsedov** [comment]
Just to note, ive started the migration, im thinking of going with a structure like this, but let it be more modular.  https://github.com/vsedov/nvim/tree/hydra_rewrite/lua/modules/editor/hydra_rewrite/hydra_modules . 


Might take a while though . >,<

**Comment by luxus** [comment]
thanks for the update ;D
i have fun to read your commits, finally someone that shares the love for 100+ plugins :D

I sometimes skip new plugins because I struggle to come up with keybindings :D

**Comment by vsedov** [comment]
I sometimes skip new plugins because I struggle to come up with keybindings :D

Tis where hydra comes in handy >,<, i have three leaders keys now . <space> -> ; -> \\ just to have more binds space .

**Comment by vsedov** [comment]
I think, what i will do for the hydra config is just refactor out anythign that
i can and go with that.

**Comment by luxus** [comment]
i see you made some progress, is the hydra_rewrite folder, stuff that's not yet rewritten?

**Comment by vsedov** [comment]
HI @luxus  I know this is late as hell but it has not been refactored now, refer to 4599411 commit to see more details , some fine tuning to be made, but majority of it has been complete - i.e people can copy pasta without issues.

**Comment by luxus** [comment]
mhh thanks for the update, i switched to astronvim
and I'm the creator of https://github.com/astronvim/astrocommunity
maybe someday i will do a hydra config for astronvim :D
