### ISSUE TITLE
Update hydra reference to nvim-island/hydra.nvim

### ISSUE THREAD

**Issue by miversen33** [vsedov/nvim#74]
I would highly advise you update your hydra reference [off my fork](https://github.com/vsedov/nvim/blob/master/lua/modules/editor/plugins.lua#L97-L104) ;)

My fork is highly unstable (especially since you have it pinned to a branch that [I don't have anymore](https://github.com/miversen33/hydra.nvim/branches)). My fork of basically any project is just for a PR or exploratory work and should probably be avoided unless you really like pain (such as the plugin your entire config relies on just vanishing lmao).

Good to see people are using the fork though!

**Comment by vsedov** [comment]
Ah good shout, i must of forgotten to do that, all fixed though, thanks. :shipit:
